In [2]:
import pandas as pd
import numpy as np
import pandas as pd
import csv

In [3]:
file_path = "C:\\Users\\Zenil\\Downloads\\Bonus Assignment\\train.csv"

🧠 CELL 2 – Load CSV Manually (No Pandas)

Loading CSV manually (No Pandas)

1. Imported CSV module to process csv files. 
2. Taking the data in a list as a reader
3. Creating a new variable named data and storing reader values as a list.

In [4]:
with open(file_path, "r") as file:
    reader = csv.reader(file)
    header = next(reader)
    data = list(reader)

print("Total Rows:", len(data))
print("Columns:", header)

Total Rows: 891
Columns: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

🧠 CELL 3 – Convert Age Column to Python List

In [5]:
age_index = header.index("Age")

age_list = []
for row in data:
    if row[age_index] != "":
        age_list.append(float(row[age_index]))

print("Total Valid Ages:", len(age_list))

Total Valid Ages: 714

🧠 CELL 4 – Mean, Median, Std Dev (NumPy)

In [6]:
age_array = np.array(age_list)

mean_age = np.mean(age_array)
median_age = np.median(age_array)
std_age = np.std(age_array)

print("Mean Age:", mean_age)
print("Median Age:", median_age)
print("Std Dev Age:", std_age)

Mean Age: 29.69911764705882
Median Age: 28.0
Std Dev Age: 14.516321150817316

🧠 CELL 5 – Fare Array + Top/Bottom 10%

In [8]:
fare_index = header.index("Fare")

fare_list = []
for row in data:
    fare_list.append(float(row[fare_index]))

fare_array = np.array(fare_list)

top_10_threshold = np.percentile(fare_array, 90)
bottom_10_threshold = np.percentile(fare_array, 10)

top_10 = fare_array[fare_array >= top_10_threshold]
bottom_10 = fare_array[fare_array <= bottom_10_threshold]

print("Top 10% Fare Count:", len(top_10))
print("Bottom 10% Fare Count:", len(bottom_10))

Top 10% Fare Count: 90
Bottom 10% Fare Count: 92

🧠 CELL 6 – Survival by Age Groups (NumPy Filtering)

In [9]:
survived_index = header.index("Survived")

age_group = []
survived = []

for row in data:
    if row[age_index] != "":
        age_group.append(float(row[age_index]))
        survived.append(int(row[survived_index]))

age_group = np.array(age_group)
survived = np.array(survived)

child_survival = survived[age_group < 15].mean()
adult_survival = survived[(age_group >= 15) & (age_group <= 60)].mean()
senior_survival = survived[age_group > 60].mean()

print("Child Survival:", child_survival)
print("Adult Survival:", adult_survival)
print("Senior Survival:", senior_survival)

Child Survival: 0.5769230769230769
Adult Survival: 0.39087947882736157
Senior Survival: 0.22727272727272727

                                       ===========================
                                       PART 2 – PANDAS ENGINEERING
                                       ===========================

🧠 CELL 7 – Load With Pandas

In [11]:
df = pd.read_csv(file_path)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

🧠 CELL 8 – Handle Missing Values

In [12]:
df["Age"] = df.groupby("Pclass")["Age"].transform(lambda x: x.fillna(x.median()))
df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)

C:\Users\Zenil\AppData\Local\Temp\ipykernel_30348\286935885.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)

🧠 CELL 9 – Feature Engineering

In [13]:
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
df["IsAlone"] = np.where(df["FamilySize"] == 1, 1, 0)
df["FarePerPerson"] = df["Fare"] / df["FamilySize"]

In [14]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,IsAlone,FarePerPerson
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,0,3.62500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,0,35.64165
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,1,7.92500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,0,26.55000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,1,8.05000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,1,13.00000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,1,30.00000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,NaN,S,4,0,5.86250
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,1,30.00000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,1,7.75000

🧠 CELL 10 – Categorical Binning

In [15]:
df["AgeGroup"] = pd.cut(df["Age"],
                        bins=[0,15,60,100],
                        labels=["Child","Adult","Senior"])

df["FareGroup"] = pd.qcut(df["Fare"],
                          q=3,
                          labels=["Low","Medium","High"])

In [16]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,IsAlone,FarePerPerson,AgeGroup,FareGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,0,3.62500,Adult,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,0,35.64165,Adult,High
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,1,7.92500,Adult,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,0,26.55000,Adult,High
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,1,8.05000,Adult,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,1,13.00000,Adult,Medium
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,1,30.00000,Adult,High
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,NaN,S,4,0,5.86250,Adult,Medium
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,1,30.00000,Adult,High
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,1,7.75000,Adult,Low

🧠 CELL 11 – Pivot Tables

In [17]:
print("Survival by Gender & Class")
print(pd.pivot_table(df,
                     values="Survived",
                     index="Sex",
                     columns="Pclass",
                     aggfunc="mean"))

print("\nSurvival by FareGroup & Embarked")
print(pd.pivot_table(df,
                     values="Survived",
                     index="FareGroup",
                     columns="Embarked",
                     aggfunc="mean"))

Survival by Gender & Class
Pclass         1         2         3
Sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

Survival by FareGroup & Embarked
Embarked          C         Q         S
FareGroup
Low        0.250000  0.388889  0.142202
Medium     0.538462  0.500000  0.373391
High       0.677419  0.142857  0.517949

C:\Users\Zenil\AppData\Local\Temp\ipykernel_30348\3557333128.py:9: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  print(pd.pivot_table(df,

🧠 CELL 12 – Correlation Matrix

In [18]:
numeric_df = df.select_dtypes(include=[np.number])
corr_matrix = numeric_df.corr()

corr_matrix["Survived"].sort_values(ascending=False)

Survived         1.000000
Fare             0.257307
FarePerPerson    0.221600
Parch            0.081629
FamilySize       0.016639
PassengerId     -0.005007
SibSp           -0.035322
Age             -0.047255
IsAlone         -0.203367
Pclass          -0.338481
Name: Survived, dtype: float64

🧠 CELL 13 – Top 5 Features

In [19]:
top_features = corr_matrix["Survived"].abs().sort_values(ascending=False)[1:6]
print("Top 5 Influencing Features:")
print(top_features)

Top 5 Influencing Features:
Pclass           0.338481
Fare             0.257307
FarePerPerson    0.221600
IsAlone          0.203367
Parch            0.081629
Name: Survived, dtype: float64

📊 Insight (Markdown)

1. Gender has strongest influence.
2. Pclass and Fare also strong.
3. Wealth does not dominate gender — women survival > wealthy men.

                                        =============================
                                        PART 3 – NUMPY SURVIVAL SCORE
                                        =============================

🧠 CELL 14 – Encode Variables

In [20]:
df["GenderNum"] = np.where(df["Sex"] == "female", 1, 0)
df["PclassNorm"] = 1 - (df["Pclass"] - 1)/2

🧠 CELL 15 – Normalize Numeric Columns

In [21]:
def normalize(x):
    return (x - x.min()) / (x.max() - x.min())

df["AgeNorm"] = normalize(df["Age"])
df["FareNorm"] = normalize(df["Fare"])
df["FamilyNorm"] = normalize(df["FamilySize"])

🧠 CELL 16 – Weighted Survival Score

In [22]:
w1 = 0.4  # Gender
w2 = 0.2  # Pclass
w3 = 0.1  # Age
w4 = 0.2  # Fare
w5 = 0.1  # Family

df["SurvivalScore"] = (
    w1*df["GenderNum"] +
    w2*df["PclassNorm"] +
    w3*(1-df["AgeNorm"]) +
    w4*df["FareNorm"] +
    w5*(1-df["FamilyNorm"])
)

df["Prediction"] = np.where(df["SurvivalScore"] >= 0.5, 1, 0)

🧠 CELL 17 – Evaluation Metrics (Manual NumPy)

In [23]:
y_true = df["Survived"].values
y_pred = df["Prediction"].values

TP = np.sum((y_true == 1) & (y_pred == 1))
TN = np.sum((y_true == 0) & (y_pred == 0))
FP = np.sum((y_true == 0) & (y_pred == 1))
FN = np.sum((y_true == 1) & (y_pred == 0))

accuracy = (TP + TN) / len(y_true)
precision = TP / (TP + FP)
recall = TP / (TP + FN)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

print("\nConfusion Matrix")
print(np.array([[TP, FP],
                [FN, TN]]))

Accuracy: 0.7934904601571269
Precision: 0.7532051282051282
Recall: 0.6871345029239766

Confusion Matrix
[[235  77]
 [107 472]]

📊 Insight (Markdown)

1. Model significantly outperforms random guessing (50% baseline).
2. Manual feature-weight logic captures structured survival bias.

1. Priority Rescue Profile:
   Women, children, first-class passengers.

2. Ethical Concerns:
   - Gender discrimination bias
   - Wealth-based survival prioritization
   - Algorithmic fairness in life-critical decisions

3. Insurance Context:
   Replace survival with risk score.
   Remove sensitive attributes.
   Focus on probabilistic underwriting rather than binary rescue logic.

🧠 CELL 18 – Survival by Class (Vectorized)

In [24]:
pclass = df["Pclass"].values
survived = df["Survived"].values

for cls in np.unique(pclass):
    print("Class", cls,
          survived[pclass == cls].mean())

Class 1 0.6296296296296297
Class 2 0.47282608695652173
Class 3 0.24236252545824846

🧠 CELL 19 – Predict Function

In [25]:
def predict_survival(passenger):
    gender = 1 if passenger["Sex"] == "female" else 0
    pclass = 1 - (passenger["Pclass"] - 1)/2
    
    score = (
        0.4*gender +
        0.2*pclass +
        0.1*(1-passenger["AgeNorm"]) +
        0.2*passenger["FareNorm"] +
        0.1*(1-passenger["FamilyNorm"])
    )
    
    return 1 if score >= 0.5 else 0